# FROM is used to mention the base OS of the image. It should be the first instruction in Dockerfile.
# Almalinux is exactly same as Redhat Image version 9
FROM almalinux:9
RUN dnf install telnet iputils net-tools bind-utils -y
CMD ["sleep", "2000"]